- name: Demo on using variables on playbook
  hosts: all
  vars:                            # Global variables : Variable can be accessed by all the tasks of the play      
   URL: play.google.com
  vars_files:
  - dev.vars.yml
  vars_prompt:
  - name: URLNAME
    prompt: Enter the URLNAME
    private: no
  tasks:
    - name:  Printing the value of variable
      debug:
        msg: Value of the URL is {{URL}}

    - name:  Demo to show local variables
      debug:
        msg: Value of the URL is {{URL}}
      vars:                   # Local variables
       URL: local.google.com

    - name:  Printing value of the variable which is not declared
      debug:
        msg: Name of the car is {{CARNAME}}   

    - name:  Demo to show quotes
      debug:
        msg: "{{URL}}" 

    - name:  Printing the prompt variable
      debug:
        msg: Url from the prompt variable is {{URLNAME}}


# Variables precedence
# CLI variables> local variables > File variables > Global variables

# If you try to print the variables which is not declared, it will throw an error.
  
  # - name:  Demo to show local variables
  #    ansible.builtin.debug/debug:
  #      msg: Value of the URL is {{URL}}